DELIMITER $$
CREATE TRIGGER LICENSECURR BEFORE INSERT
ON INCLUDE
FOR EACH ROW
BEGIN
	IF
		EXISTS(SELECT *
			FROM INCLUDE
			WHERE NEW.CurriculumId = CurriculumId) 
        
		AND
        
		NOT EXISTS(
			SELECT *
			FROM COURSE, INCLUDE
			WHERE NEW.CurriculumId = CurriculumId
			AND COURSE.CCode = INCLUDE.CourseCode
			AND LicenseOrNot = (SELECT LicenseOrNot
			FROM COURSE
			WHERE COURSE.CCode = NEW.CourseCode)
        )
    THEN
		SIGNAL SQLSTATE '02000' SET MESSAGE_TEXT = 'INSERT WARNING - CURRICULUM DOES NOT MATCHING WITH COURSE';
    END IF;
END
$$ DELIMITER ;