
DELIMITER $$
CREATE TRIGGER FacultyMemberTotalTrigger BEFORE INSERT
ON FACULTY_MEMBER
FOR EACH ROW
BEGIN
IF
	FacultyMemberController(NEW.FMId)= 0
THEN
	SIGNAL SQLSTATE '02000' SET MESSAGE_TEXT = 'UPDATE WARNING - RESEARCH ASSISTANT EXISTS IN EDUCATOR TABLE';
END IF;
END;

$$ DELIMITER ;