/* 0 DAN INCLUDE OLUSTURMAK ISTEDIGIMIZDE OLUSTURMAYI ENGELLIYOR*/

DELIMITER $$
CREATE TRIGGER LicenseCurrControl BEFORE INSERT
ON INCLUDE
FOR EACH ROW
BEGIN 
	IF
		
		NOT EXISTS(
			SELECT *
			FROM COURSE,INCLUDE
			WHERE INCLUDE.CourseCode = COURSE.CCode AND NEW.CurriculumId = INCLUDE.CurriculumId  AND LicenseOrNot = LicenseCountCalculator(NEW.CourseCode)
			GROUP BY CurriculumId,LicenseOrNot
		)
				

	THEN
		SIGNAL SQLSTATE '02000' SET MESSAGE_TEXT = 'INSERT WARNING - LICENSE CONTROL';
    END IF;
END;
$$ DELIMITER ;

DELIMITER $$
CREATE TRIGGER LicenseCurrControlUpdate BEFORE UPDATE
ON INCLUDE
FOR EACH ROW
BEGIN 
	IF
		
		NOT EXISTS(
			SELECT *
			FROM COURSE,INCLUDE
			WHERE INCLUDE.CourseCode = COURSE.CCode AND NEW.CurriculumId = INCLUDE.CurriculumId  AND LicenseOrNot = LicenseCountCalculator(NEW.CourseCode)
			GROUP BY CurriculumId,LicenseOrNot
		)
				

	THEN
		SIGNAL SQLSTATE '02000' SET MESSAGE_TEXT = 'UPDATE WARNING - LICENSE CONTROL';
    END IF;
END;
$$ DELIMITER ;