SELECT KEYWORDS.`Keyword`,RESEARCH_AREA.`ResearchArea`, KEYWORDS.`CourseCode` AS 'KeyCourseCode' , COURSE.`CCode` AS 'COURSECourseCode', INCLUDE.`CourseCode` AS 'INCLUDECourseCode' , INCLUDE.`CurriculumId` AS 'INCLUDECurriculumId',
		CURRICULUM.`CurId` AS 'CURRICULUMCurId', CURRICULUM.`DCode` AS `CURRICULUMDeptCode`, DEPT.`DCode` AS 'DEPTDCode',FACULTY_MEMBER.`DeptCode` AS 'FACMEMBERDeptCode',FACULTY_MEMBER.`FMId` AS 'FACMEMBERId',
        RESEARCH_AREA.`FMId` AS 'RESAREAFMId'
        
     
        
        
FROM INCLUDE,COURSE,CURRICULUM,DEPT,FACULTY_MEMBER,KEYWORDS,RESEARCH_AREA
WHERE 
	INCLUDE.`CourseCode` = COURSE.`CCode` AND
    COURSE.`CCode` = KEYWORDS.`CourseCode` AND
    INCLUDE.`CurriculumId` = CURRICULUM.`CurId` AND
    CURRICULUM.`DCode` = DEPT.`DCode` AND
    DEPT.`Dcode` = FACULTY_MEMBER.`DeptCode` AND 
    FACULTY_MEMBER.`FMId` = RESEARCH_AREA.`FMId` AND
	Keyword = ResearchArea 

ORDER BY KeyCourseCode
