/*FAC MEMBERLARIN RESEARCH AREA LARINI COUNT ILE YAZDIR ???*/
SELECT count(),FACULTY_MEMBER.FMId
FROM RESEARCH_AREA,FACULTY_MEMBER
WHERE RESEARCH_AREA.FMId = FACULTY_MEMBER.FMId



/*SELECT `COURSE`.`CCode` AS 'CourseCode', `FACULTY_MEMBER`.`FMId` AS 'FacultyMemberId'
FROM INCLUDE,COURSE,CURRICULUM,DEPT,FACULTY_MEMBER,KEYWORDS,RESEARCH_AREA
WHERE INCLUDE.`CourseCode` = COURSE.`CCode` AND
    COURSE.`CCode` = KEYWORDS.`CourseCode` AND
    INCLUDE.`CurriculumId` = CURRICULUM.`CurId` AND
    CURRICULUM.`DCode` = DEPT.`DCode` AND
    DEPT.`Dcode` = FACULTY_MEMBER.`DeptCode` AND 
    FACULTY_MEMBER.`FMId` = RESEARCH_AREA.`FMId` AND
	Keyword = ResearchArea 
    
ORDER BY `KEYWORDS`.`CourseCode`
    */
    /*
     AND 
    MatchingPercent IN
	(
    SELECT count(*)
	WHERE Keyword = ResearchArea
	)

    */