DELIMITER $$
CREATE TRIGGER MentoredAddition AFTER INSERT
ON RESEARCH_ASSISTANT
FOR EACH ROW
BEGIN
	UPDATE PROFESSOR SET NofMentoredStudent = NofMentoredStudent+1 WHERE NEW.ProfId = PROFESSOR.ProfessorId;
END;
$$ DELIMITER ;


DELIMITER $$
CREATE TRIGGER MentoredAdditionUpdate AFTER UPDATE
ON RESEARCH_ASSISTANT
FOR EACH ROW
BEGIN
	UPDATE PROFESSOR SET NofMentoredStudent = NofMentoredStudent+1 WHERE NEW.ProfId = PROFESSOR.ProfessorId;
END;
$$ DELIMITER ;
