ALTER TABLE COLLEGE
ADD CONSTRAINT DeanIdFK
FOREIGN KEY (DeanId) REFERENCES PROFESSOR(`ProfessorId`)
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE DEPT
ADD CONSTRAINT CollegeNameFK
FOREIGN KEY (CollegeName) REFERENCES COLLEGE(`CName`)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE DEPT
ADD CONSTRAINT DeptChairFK
FOREIGN KEY (ChairId) REFERENCES EDUCATOR(`EducatorId`)
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE CURRICULUM
ADD CONSTRAINT CurrDCodeFK
FOREIGN KEY (DCode) REFERENCES DEPT(`DCode`)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE SECTION
ADD CONSTRAINT SecCCode
FOREIGN KEY (CourseCode) REFERENCES COURSE(`CCode`)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE STUDENT
ADD CONSTRAINT StudentDCode
FOREIGN KEY (`DeptCode`) REFERENCES DEPT(`DCode`)
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE FACULTY_MEMBER
ADD CONSTRAINT FacultyMDCode
FOREIGN KEY (DeptCode) REFERENCES DEPT(`DCode`)
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE THESE
ADD CONSTRAINT ThedeFMId
FOREIGN KEY (FMId) REFERENCES FACULTY_MEMBER(`FMId`)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE INCLUDE
ADD CONSTRAINT IncludeCurId
FOREIGN KEY (CurriculumId) REFERENCES CURRICULUM(`CurId`)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE INCLUDE
ADD CONSTRAINT IncludeCCode
FOREIGN KEY (CourseCode) REFERENCES COURSE(`CCode`)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TAKES
ADD CONSTRAINT TakesStudentId
FOREIGN KEY (StudentId) REFERENCES STUDENT (`StudentId`)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TAKES
ADD CONSTRAINT TakesSecId
FOREIGN KEY (SectionId) REFERENCES SECTION (`SecId`)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE RESEARCH_AREA
ADD CONSTRAINT ResAreaFMId
FOREIGN KEY (FMId) REFERENCES FACULTY_MEMBER(`FMId`)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE KEYWORDS
ADD CONSTRAINT KeywordCCode
FOREIGN KEY (CourseCode) REFERENCES COURSE(`CCode`)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE MANDATORY
ADD CONSTRAINT MandatoryCCode
FOREIGN KEY (MandatoryCourseCode) REFERENCES COURSE(`CCode`)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE OPTIONALCOURSE
ADD CONSTRAINT OptionalCCode
FOREIGN KEY (OptionalCourseCode) REFERENCES COURSE(`CCode`)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE EDUCATOR
ADD CONSTRAINT EducatorFMId
FOREIGN KEY (EducatorId) REFERENCES FACULTY_MEMBER(`FMId`)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE RESEARCH_ASSISTANT
ADD CONSTRAINT RAFMId
FOREIGN KEY (ResearchAsstFMId) REFERENCES FACULTY_MEMBER(`FMId`)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE RESEARCH_ASSISTANT
ADD CONSTRAINT RAStudentId
FOREIGN KEY (ResearchAsstStudentId) REFERENCES STUDENT(`StudentId`)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE RESEARCH_ASSISTANT
ADD CONSTRAINT RAProfId
FOREIGN KEY (ProfId) REFERENCES PROFESSOR(`ProfessorId`)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE PROFESSOR
ADD CONSTRAINT ProfessorIdFK
FOREIGN KEY (ProfessorId) REFERENCES EDUCATOR (`EducatorId`)
ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE ASSOCIATE_PROFESSOR
ADD CONSTRAINT AssociateProfIdFK
FOREIGN KEY (AssociateProfId) REFERENCES EDUCATOR (`EducatorId`)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE ASSISTANT_PROFESSOR
ADD CONSTRAINT AssistantProfIdFK
FOREIGN KEY (AssistantProfId) REFERENCES EDUCATOR(`EducatorId`)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE INSTRUCTOR
ADD CONSTRAINT InstructorIdFK
FOREIGN KEY (InstructorId) REFERENCES EDUCATOR(`EducatorId`)
ON DELETE CASCADE ON UPDATE CASCADE;
