INSERT INTO `keywords`
(`CourseCode`,`Keyword`)
VALUES
('CE101', 'C Programlama'),
('CE101', 'Paralel Algoritmalar'),
('CE101', 'Dağıtık Sistemler'),
('CE101', 'Temel Mühendislik'),
('CE102', 'Kotlin Programlama'),
('CE102', 'API Management'),
('CE102', 'Temel Mühendislik'),
('AI101', 'Temel Mühendislik'),
('AI101', 'Görüntü İşleme'),
('AI101', 'Genetik ALgoritmalar'),
('AI101', 'Python Programlama'),
('AI101', 'Arama Yöntemleri'),
('AI102', 'İleri Fizik Yöntemleri'),
('AI102', 'Teorem Bilgisi'),
('AI102', 'Devre Analizi Teknikleri'),
('CE103', 'Doğaçlama'),
('CE103', 'Temel İletişim Becerileri'),
('SE101', 'Semantic Web Analizi'),
('SE101', 'JS Programlama'),
('SE101', 'Temel Framework Kullanımı'),
('SE101', 'Temel Mühendislik'),
('SE102', 'Temel Mühendislik'),
('SE102', 'Arama Yöntemleri'),
('SE102', 'SOLID Bilgisi'),
('SE102', 'Algoritma Karmaşıklık Analizi'),
('SE103', 'Manevra Teknikleri'),
('SE103', 'Kazaazede Analizi'),
('SE103', 'Yaralanma Müdahaleleri'),
('SE103', 'Pozisyon Bilgileri'),
('YC101', 'İleri Mühendislik'),
('YC101', 'Derin Öğrenme'),
('YC101', 'Uzaysal Filtreler'),
('YC101', 'Biyometri'),
('YC102', 'Algoritma Analizi'),
('YC102', 'Algoritma Tasarımı'),
('YC102', 'İleri Mühendislik'),
('YA101', 'Örnekleme Teknikleri'),
('YA101', 'Veri Analizi'),
('YA101', 'Yayın Etiği Kuralları'),
('YS103', 'İleri Mühendislik'),
('YS103', 'Algoritma Tasarımı'),
('YS103', 'Genetik Algoritmalar'),
('YS103', 'Yapay Sinir Ağları'),
('YS103', 'Doğal Dil İşleme'),
('YS103', 'Makine Öğrenmesi'),
('YS103', 'Derin Öğrenme')

