CREATE TABLE TAKES
(
StudentId BIGINT NOT NULL,
SectionId INT NOT NULL,
GRADE VARCHAR(2),

PRIMARY KEY (StudentId,SectionId),

CHECK(GRADE = 'AA' OR GRADE = 'BA' OR GRADE = 'BB' OR GRADE = 'CB' OR GRADE = 'CC' OR GRADE='DC' OR GRADE = 'FD' OR GRADE = 'FF')

)